version: '2'

services:
  web-ui-v2:
    build: web-ui-v2
    ports:
      - "8001:4200"
    links:
      - "image-server-api"

  image-server-api:
    build: image-server-api
    ports :
      - "8002:3000"
    links:
      - mongo
      - rabbitmq

  face-finder:
    build: face-finder
    links:
      - rabbitmq
      - redis

  mongo:
    image: mongo
    ports :
       - "27017:27017"

  rabbitmq:
    image: rabbitmq:alpine
    ports:
     - "5672:5672"
     - "25672:25672"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
