version: '2'

services:
  web-ui-v2:
    build: web-ui-v2
    ports:
      - "8001:4200"
    links:
      - "image-server-api"

  image-server-api:
    build: image-server-api
    ports :
      - "8002:3000"
    links:
      - mongo
      - kafka

  face-finder:
    build: face-finder
    links:
      - kafka
      - redis

  mongo:
    image: mongo
    ports :
       - "27017:27017"

 zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka

    depends_on:
      - zookeeper
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  redis:
    image: redis:alpine
