FROM node:7

RUN git clone https://github.com/multimedia-term-project/image-server-api.git

WORKDIR  image-server-api/image-server-api/

COPY aws.config.json .

CMD ["echo", "$(pwd)"]

RUN npm install

EXPOSE 3000

# Serve the app
CMD ["node", "app.js"]
