FROM python:3.6-alpine

RUN git clone https://github.com/multimedia-term-project/face-finder.git

WORKDIR face-finder

COPY ../aws.config.json .

RUN pip install -r requirements.txt

# Serve the app
CMD ["python", "main.py"]
